version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: 
          name: Replace coveralls repo token
          command: sed -i "s/COVERALLS\_TOKEN/$COVERALLS_TOKEN/g" .coveralls.yml
      - run:
          name: Run tests and create coverage report
          command: npm run test-nowatch && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
      - run:
          name: Create .env file
          command: echo REACT_APP_USER_NAME="$REACT_APP_USER_NAME"\nREACT_APP_WEATHER_API_KEY="$REACT_APP_WEATHER_API_KEY"\nREACT_APP_GEOCAGE_API_KEY="$REACT_APP_GEOCAGE_API_KEY" >> ./.env
      - run:
          name: Build
          command: npm run build --prod
      - run:
          name: generate-firebaserc
          command: cp .firebaserc.example .firebaserc
      - run:
          name: modify-firebaserc
          command: sed -i "s/\[YOUR\-PROJECT\-ID\]/$FIREBASE_PROJECT_ID/g" .firebaserc
      - run:
          name: Firebase deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"